---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - role: finaldes.ansible_docker_ce
      branch: stable
      become: true
      compose: true
      compose_version: "1.25.5"
