---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu22.04
    image: finaldes/docker-ubuntu-ansible:jammy-20230215
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu20.04
    image: finaldes/docker-ubuntu-ansible:focal-20230215
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu18.04
    image: finaldes/docker-ubuntu-ansible:bionic-20230215
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
# - name: ubuntu16.04
#   image: finaldes/docker-ubuntu-ansible:xenial-20210226-1810
#   pre_build_image: true
#   privileged: true
#   volumes:
#     - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
