---
- name: Allow install apt over https
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common
- name: Import the public key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
- name: Add repository ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ branch }}'
    state: present
    filename: 'docker'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
- name: Add repository debian
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} {{ branch }}'
    state: present
    filename: 'docker'
    update_cache: yes
  when: ansible_distribution == 'Debian'
- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
- name: Add user to 'docker' group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    state: present
    append: true
- name: Setup docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: compose