---
- name: Allow install apt over https
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - python3-debian
- name: Add docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: ["{{ ansible_docker_ce_branch | lower }}"]
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin 
        - docker-compose-plugin
- name: Add user to 'docker' group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    state: present
    append: true
- name: Setup v1 docker-compose 
  ansible.builtin.get_url:
    url: "{{ ansible_docker_ce_download_root_path }}{{ ansible_docker_ce_v1_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "0755"
    checksum: sha256:{{ ansible_docker_ce_download_root_path }}{{ ansible_docker_ce_v1_compose_version }}/docker-compose-Linux-x86_64.sha256
  when: ansible_docker_ce_compose
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: "0755"
    owner: root
    group: root
  register: docker_compose_path
  when: ansible_docker_ce_compose
- name: Setup new docker-compose
  ansible.builtin.get_url:
    url: "{{ ansible_docker_ce_download_root_path }}{{ ansible_docker_ce_compose_version }}/docker-compose-linux-x86_64"
    dest: "{{ docker_compose_path.path }}/docker-compose"
    mode: "0755"
    checksum: sha256:{{ ansible_docker_ce_download_root_path }}{{ ansible_docker_ce_compose_version }}/docker-compose-linux-x86_64.sha256
  when: ansible_docker_ce_compose
