---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - role: "ansible-docker-ce"
      branch: "edge"
      become: true
      compose: true
      compose_version: "1.25.5"
