---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - role: "ansible-docker-ce"
      ansible_docker_ce_branch: "edge"
      ansible_docker_ce_compose: true
      ansible_docker_ce_compose_version: "1.29.2"
      became: true
